version: 2

sources:
  - name: raw
    description: Raw tables loaded by Python ingestion scripts
    schema: main
    tables:
      - name: raw_bus_shelters
        description: Raw bus shelter locations data from Philadelphia's open data portal
        columns:
          - name: objectid
            description: Unique identifier for each shelter
          - name: site
            description: Location name/description
          - name: siteid
            description: Site identifier
          - name: stopid
            description: Stop identifier
          - name: lat
            description: Latitude coordinate
          - name: long_
            description: Longitude coordinate
          - name: productgroup
            description: Product group classification
          - name: x
            description: X coordinate
          - name: y
            description: Y coordinate

models:
  - name: stg_bus_shelters
    description: Cleaned and renamed bus shelter locations
    columns:
      - name: shelter_id
        description: Unique identifier for each shelter
        data_tests:
          - unique
          - not_null
      - name: location_name
        description: Location name/description
      - name: site_id
        description: Site identifier
      - name: stop_id
        description: Stop identifier
      - name: latitude
        description: Latitude coordinate
        data_tests:
          - not_null
      - name: longitude
        description: Longitude coordinate
        data_tests:
          - not_null
      - name: product_group
        description: Product group classification
      - name: x_coordinate
        description: X coordinate
      - name: y_coordinate
        description: Y coordinate

  - name: stg_gtfs_routes
    description: Staging model for SEPTA routes from GTFS feed
    columns:
      - name: route_id
        description: Unique identifier for each route
        tests:
          - unique
          - not_null
      - name: agency_id
        description: Reference to the agency operating this route
        tests:
          - not_null
          - relationships:
              to: ref('stg_gtfs_agency')
              field: agency_id
      - name: route_type
        description: Numeric code representing the route type/mode
        tests:
          - not_null
      - name: mode_name
        description: Human-readable name for the route type/mode
        tests:
          - not_null
      - name: data_source
        description: Source of the route data (bus or rail)
        tests:
          - not_null
          - accepted_values:
              values: ['bus', 'rail']

  - name: stg_gtfs_agency
    description: Staging model for SEPTA agencies from GTFS feed
    columns:
      - name: agency_id
        description: Unique identifier for each agency
        tests:
          - unique
          - not_null
      - name: agency_name
        description: Name of the transit agency
        tests:
          - not_null
      - name: data_source
        description: Source of the agency data (bus or rail)
        tests:
          - not_null
          - accepted_values:
              values: ['bus', 'rail']
